library:
  source-dirs: src
tests:
  huffman-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huffman
copyright: 2019 mduerig
dependencies:
- binary
- mtl
- containers
- base >= 4.7 && < 5
name: huffman
version: 0.1.0.0
extra-source-files:
- README.md
author: mduerig
github: mduerig/huffman
license: ASL-2.0
executables:
  huffman-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huffman
description: Please see the README on GitHub at <https://github.com/mduerig/huffman#readme>
